In [ ]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import CategoricalNB

In [ ]:
#NOTE: using laplace smoothing 
from sklearn.naive_bayes import CategoricalNB

model = CategoricalNB(alpha=1.0)

In [32]:
dataset =  pd.read_csv('play_tennis_20.csv')
dataset

     Outlook Temperature Humidity    Wind PlayTennis
0      Sunny         Hot     High    Weak         No
1      Sunny         Hot     High  Strong         No
2   Overcast         Hot     High    Weak        Yes
3       Rain        Mild     High    Weak        Yes
4       Rain        Cool   Normal    Weak        Yes
5       Rain        Cool   Normal  Strong         No
6   Overcast        Cool   Normal  Strong        Yes
7      Sunny        Mild     High    Weak         No
8      Sunny        Cool   Normal    Weak        Yes
9       Rain        Mild   Normal    Weak        Yes
10     Sunny        Mild   Normal  Strong        Yes
11  Overcast        Mild     High  Strong        Yes
12  Overcast         Hot   Normal    Weak        Yes
13      Rain        Mild     High  Strong         No
14     Sunny        Cool     High  Strong         No
15  Overcast        Cool     High    Weak        Yes
16      Rain         Hot   Normal    Weak        Yes
17     Sunny        Mild     High  Strong         No
18  Overcast        Mild   Normal    Weak        Yes
19      Rain        Cool     High    Weak         No

# # Problem 1: 
#       When outlook = Sunny, Temp = Hot , Humidity = High, Wind= Weak
#       --> find the probability that player will play tennis ?

In [33]:
dataset['PlayTennis'].value_counts()

PlayTennis
Yes    12
No      8
Name: count, dtype: int64

In [34]:
#NOTE : probability of Yes and No
prob_yes = 12/20
prob_no = 8 / 20

In [35]:
dataset['Outlook'].value_counts()

Outlook
Sunny       7
Rain        7
Overcast    6
Name: count, dtype: int64

In [36]:
pd.crosstab(dataset['Outlook'], dataset['PlayTennis'])

PlayTennis  No  Yes
Outlook
Overcast     0    6
Rain         3    4
Sunny        5    2

In [37]:
#NOTE: prob when no
prob_overcase_no = 0 / 8
prob_rain_no = 3 / 8
prob_sunny_no = 5 / 8

#NOTE: prob when yes
prob_overcase_yes = 6 / 12
prob_rain_yes = 4 / 12
prob_sunny_yes = 2 / 12

In [38]:
dataset['Temperature'].value_counts()

Temperature
Mild    8
Cool    7
Hot     5
Name: count, dtype: int64

In [39]:
pd.crosstab(dataset['Temperature'], dataset['PlayTennis'])

PlayTennis   No  Yes
Temperature
Cool          3    4
Hot           2    3
Mild          3    5

In [40]:
#NOTE: prob when no
prob_Cool_no = 3 / 8 
prob_Hot_no = 2 / 8 
prob_Mild_no = 3 / 8 

#NOTE: prob when yes
prob_Cool_yes = 4 / 12 
prob_Hot_yes = 3 / 12 
prob_Mild_yes = 5 / 12

In [41]:
dataset['Humidity'].value_counts()

Humidity
High      11
Normal     9
Name: count, dtype: int64

In [42]:
pd.crosstab(dataset['Humidity'], dataset['PlayTennis'])

PlayTennis  No  Yes
Humidity
High         7    4
Normal       1    8

In [43]:
#NOTE: prob when no
prob_High_no = 7 /8 
prob_Normal_no = 1 / 8

prob_High_yes = 4 / 12 
prob_Normal_yes = 8 / 12

In [44]:
dataset['Wind'].value_counts()

Wind
Weak      12
Strong     8
Name: count, dtype: int64

In [45]:
pd.crosstab(dataset['Wind'], dataset['PlayTennis'])

PlayTennis  No  Yes
Wind
Strong       5    3
Weak         3    9

In [48]:
#NOTE: prob when no
prob_Strong_no = 5 / 8 
prob_Weak_no = 3 / 8

#NOTE: prob when yes
prob_Strong_yes = 3 / 12
prob_Weak_yes = 9 / 12

# 🟢 Scenario 1: Weather App Decision System

You are building a small ML system for a sports academy.
Every morning, the system predicts whether the academy should schedule outdoor tennis practice.

🌤 New Weather Conditions:

Outlook = Rain

Temperature = Cool

Humidity = Normal

Wind = Strong

❓ Question:

Using Naive Bayes, should the academy schedule tennis practice?

👉 Calculate:

P(Yes | conditions)

P(No | conditions)

Then decide the final class.

In [50]:
py = prob_yes * prob_rain_yes * prob_Cool_yes * prob_Normal_yes * prob_Strong_yes 
print(f"The probability of yes is {py}")

pn = prob_yes * prob_rain_no * prob_Cool_no * prob_Normal_no * prob_Strong_no 
print(f"The probability of No is {pn}")

The probability of yes is 0.011111111111111108
The probability of No is 0.006591796874999999

In [51]:
if(py > pn):
    print("Players will play tennis !")
elif(py == pn):
    print("There is equal chance player will play tennis !")
else:
    print("Players won't play tennis !")

Players will play tennis !